### ISSUE TITLE
Configure Error in Genius TCAD

### ISSUE THREAD

**Issue by gjdapromise** [cogenda/Genius-TCAD-Open#28]
Dear All,

./waf --prefix=/home/gj/Downloads/Softwares/Genius-TCAD-Open-master --with-petsc-dir=/home/gj/Downloads/Softwares/petsc-3.5.4 --with-petsc-arch=$PETSC_ARCH configure

I am running above command which is giving me following error.

Setting top to                           : /home/gj/Downloads/Softwares/Genius-TCAD-Open-master 
Setting out to                           : /home/gj/Downloads/Softwares/Genius-TCAD-Open-master/build/default 
Checking for 'icc' (c compiler)          : not found 
Checking for 'gcc' (c compiler)          : ok 
Checking for 'icpc' (c++ compiler)       : not found 
Checking for 'g++' (c++ compiler)        : ok 
Checking for 'ifort' (fortran compiler)  : not found 
Checking for 'gfortran' (fortran compiler) : ok 
Checking for program git                   : not found 
Setting version string                     : 20170112 
Detecting optimization options             : -O2 -unroll -msse3 
Checking for visibility flags              : yes 
Checking for size of double                : yes 
Checking for size of float                 : yes 
Checking for size of int                   : yes 
Checking for size of long int              : yes 
Checking for size of long long int         : yes 
Checking for size of short int             : yes 
Checking for size of void *                : yes 
Checking for header fcntl.h                : yes 
Checking for header float.h                : yes 
Checking for header fenv.h                 : yes 
Checking for header limits.h               : yes 
Checking for header stddef.h               : yes 
Checking for header stdlib.h               : yes 
Checking for header string.h               : yes 
Checking for header stdio.h                : yes 
Checking for header assert.h               : yes 
Checking for header sys/time.h             : yes 
Checking for header sys/types.h            : yes 
Checking for header sys/stat.h             : yes 
Checking for header stdlib.h               : yes 
Checking for header string.h               : yes 
Checking for header memory.h               : yes 
Checking for header strings.h              : yes 
Checking for header inttypes.h             : yes 
Checking for header stdint.h               : yes 
Checking for header unistd.h               : yes 
Checking for header tr1/unordered_map      : yes 
Checking for header tr1/unordered_set      : yes 
Checking for header unordered_map          : not found 
Checking for header unordered_set          : not found 
Checking for header limits                 : yes 
Checking for c++ namespaces                : yes 
Checking for std::sstream                  : yes 
Checking for library m                     : yes 
Using Petsc version 3.5.4
Traceback (most recent call last):
  File "/home/gj/Downloads/Softwares/Genius-TCAD-Open-master/.waf-1.6.4-824951e80a41e1b5242645f254d7d36f/waflib/Scripting.py", line 93, in waf_entry_point
    run_commands()
  File "/home/gj/Downloads/Softwares/Genius-TCAD-Open-master/.waf-1.6.4-824951e80a41e1b5242645f254d7d36f/waflib/Scripting.py", line 145, in run_commands
    run_command(cmd_name)
  File "/home/gj/Downloads/Softwares/Genius-TCAD-Open-master/.waf-1.6.4-824951e80a41e1b5242645f254d7d36f/waflib/Scripting.py", line 138, in run_command
    ctx.execute()
  File "/home/gj/Downloads/Softwares/Genius-TCAD-Open-master/.waf-1.6.4-824951e80a41e1b5242645f254d7d36f/waflib/Configure.py", line 124, in execute
    super(ConfigurationContext,self).execute()
  File "/home/gj/Downloads/Softwares/Genius-TCAD-Open-master/.waf-1.6.4-824951e80a41e1b5242645f254d7d36f/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/gj/Downloads/Softwares/Genius-TCAD-Open-master/.waf-1.6.4-824951e80a41e1b5242645f254d7d36f/waflib/Context.py", line 127, in recurse
    user_function(self)
  File "/home/gj/Downloads/Softwares/Genius-TCAD-Open-master/wscript", line 684, in configure
    config_petsc()
  File "/home/gj/Downloads/Softwares/Genius-TCAD-Open-master/wscript", line 609, in config_petsc
    inc_dirs.append(os.path.join(base_dir, 'include'))
UnboundLocalError: local variable 'inc_dirs' referenced before assignment

Thanks & Regards
GJ

**Comment by andruo** [comment]
Hi, gjdapromise. You can fix that by adding string inc_dirs = [] before 'for' loop (line 606) in the wscript file.
